version: '3.1'

networks:
  main:
    driver: bridge

services:

  postgres8:
    image: postgres:8.4
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_migrate_test
    networks:
      main:
        aliases:
          - postgres.local

  postgres9.0:
    image: postgres:9.0
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_migrate_test
    networks:
      main:
        aliases:
          - postgres.local

  postgres9.6:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_migrate_test
    networks:
      main:
        aliases:
          - postgres.local

  postgres10:
    image: postgres:10.7
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_migrate_test
    networks:
      main:
        aliases:
          - postgres.local

  postgres11:
    image: postgres:11.2
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_migrate_test
    networks:
      main:
        aliases:
          - postgres.local

  node:
    image: node:8.15.1
    volumes:
      - $PWD:/var/lib/db-migrate-pg
    working_dir: /var/lib/db-migrate-pg
    environment:
      - PGHOST=postgres.local
      - PGUSER=postgres
    networks:
      - main
    command: npm test
